### ISSUE TITLE
Submitting note crashes the page with error 500

### ISSUE THREAD

**Issue by BorderKeeper** [ARCOMM/ARCHUB#193]
Go to http://178.62.14.130:81/hub/missions/1059
Write a note of any kind ideally with some bulletpoints
Click Submit
![image](https://user-images.githubusercontent.com/7063238/199776750-d275961d-114d-49dd-b7aa-38e46b1b16b4.png)

**Comment by BorderKeeper** [comment]
Edit: The note appeared after refresh. The crash happened but did not prevent upload.

**Comment by TomBurch** [comment]
Fixed by https://github.com/TomBurch/ARCHUB-V2/commit/622c243bdae7db5e8b2e1458f2913d7ed6d8c56a
