### ISSUE TITLE
Add Markdown text and link to comment/note boxes in HUB.

### ISSUE THREAD

**Issue by Feebee21** [ARCOMM/ARCHUB#21]
Not easily understood how to do fancy text stuff.

Literally a perfect example right here. :)

![Markdown](https://user-images.githubusercontent.com/19499448/94368573-655d8480-00aa-11eb-8e00-c4c5006f76bb.png)

**Comment by puzzleddev** [comment]
The markdown flavour used is: "Showdown - Vanilla" from version 1.8.6. We may want to think about standardizing it to something more common, mostly because I don't think there is a source for what that is exactly.

**Comment by BorderKeeper** [comment]
That is beyond the scope of this ticket. I would move it to a different one and have this one focus on just the icon with some hint text.

**Comment by TomBurch** [comment]
@puzzleddev You can see the features of markdown flavours here
https://gist.github.com/vimtaai/99f8c89e7d3d02a362117284684baa0f
