### ISSUE TITLE
Add filtering to mission screen

### ISSUE THREAD

**Issue by Viking181** [ARCOMM/ARCHUB#23]
Add filtering beyond "played" and "unplayed" for mission testers etc. Suggest breaking it down further into Played, Verified, Untested. Would make figuring out what needs testing substantially easier at a glance.

**Comment by BorderKeeper** [comment]
This will require some ui design beforehand as it would make new missions and my missions tabs a bit obsolete.

**Comment by TomBurch** [comment]
Duplicated in https://github.com/ARCOMM/ARCHUB/issues/38
