### ISSUE TITLE
Add panel to upload missions

### ISSUE THREAD

**Issue by leotht** [ARCOMM/ARCHUB#24]
Create a panel thing that pops up when you click on Upload. It should include something like "Hey, before you upload your mission, be sure to check the Mission Checklist (link to the checklist)". Then, under it, an actual button to upload it. This is supposed to make the checklist more visible as some people don't even know that it exists, and also enforces people to improve their quality based on our standard.

**Comment by TomBurch** [comment]
Doesn't seem necessary - creates annoyance for uploading missions and new mission makers should already be made familiar with the checklist
