### ISSUE TITLE
Uploading a mission with missing/incomplete briefings break their archub page

### ISSUE THREAD

**Issue by Freddo3000** [ARCOMM/ARCHUB#30]
Examples:

https://arcomm.co.uk/hub/missions/851

https://arcomm.co.uk/hub/missions/819

https://arcomm.co.uk/hub/missions/860

**Comment by WirelessPillow** [comment]
Examples are missing, can you upload one with a test tag for reference

**Comment by TomBurch** [comment]
Potentially covered by https://github.com/ARCOMM/ARCHUB/pull/34

Other issues can be fixed as they're discovered
