### ISSUE TITLE
Add filter functionality for mission listings

### ISSUE THREAD

**Issue by Freddo3000** [ARCOMM/ARCHUB#38]
Filters:

* Verified/Unverified
* Mission type
* Terrain
* Addons used
* Mission name
* Author

This should be accessible via dropdowns and text fields.

**Comment by TomBurch** [comment]
Filter functinality added through https://github.com/ARCOMM/ARCHUB/pull/148 https://github.com/ARCOMM/ARCHUB/pull/152 https://github.com/ARCOMM/ARCHUB/pull/161
Further filters can be added as requested
