### ISSUE TITLE
Change mission states from Verified/Unverified to Broken/Needs Testing/Verified

### ISSUE THREAD

**Issue by Freddo3000** [ARCOMM/ARCHUB#40]
This should add some additional clarity for the testing state that the mission. Missions should default to "Needs Testing", from which testers can then change the state to either Verified or Broken. If marked as broken, the mission should reset to Needs Testing when a new version is uploaded.

**Comment by WirelessPillow** [comment]
This needs to be discussed in a meeting before agreed upon.

**Comment by TomBurch** [comment]
Already covered by notes + mission testing spreadsheet.
