### ISSUE TITLE
Change GCS naming scheme to allow punctuation in mission names

### ISSUE THREAD

**Issue by TomBurch** [ARCOMM/ARCHUB#44]
If you have any punctuation in mission name it gets included in the filepath when creating/retrieving GCS files, which fails silently and throws a 404 when you try to download the mission

Mission name: 
`Land of the Lost?`
PBO: 
![image](https://user-images.githubusercontent.com/28692063/110369730-b5217e00-8042-11eb-823f-c37b22583c1b.png)
GCS: 
![image](https://user-images.githubusercontent.com/28692063/110369810-d08c8900-8042-11eb-9c82-ff20d9122e9b.png)

![image](https://user-images.githubusercontent.com/28692063/110370085-26f9c780-8043-11eb-93e4-30038c5d2e6f.png)

Suggestion: GCS files should have a similar naming scheme to the PBO itself (which is held to formatting standards when uploading) to ensure they are valid, rather than generating a new name

**Comment by Freddo3000** [comment]
IMO mission naming and such should be unlinked from the PBO name. One can check the mission name and [mission type](https://community.bistudio.com/wiki/Multiplayer_Game_Types) from the mission.sqm. This removes the problems surrounding PBO naming, allowing whatever to be uploaded. Missions can then be renamed to whatever name automatically by ARCHUB, which it already seems to do to some extent with the version names and shortened author names.

**Comment by BorderKeeper** [comment]
https://github.com/ARCOMM/ARCHUB/pull/51
