### ISSUE TITLE
Add an automatic Discord ping functionality when a tester publishes notes to mission

### ISSUE THREAD

**Issue by matuzalem-svk** [ARCOMM/ARCHUB#47]
When a mission tester posts new notes for a mission, make it so that the mission maker gets pinged on Discord automatically,

An example ping might looks like this:
@mission-maker-user#1234 New testing notes have been published for your mission **Hello, Mission!**.

**Comment by BorderKeeper** [comment]
Sadly that would be very difficult since we only have mapping from stream to archub not discord to archub. That mapping has been done in ARCHUB v2 though.
